-- 잠깐 identity 제약 풀기
alter table product_ingredients alter column id set generated by default;

-- 1) 충돌 방지용으로 큰 값으로 임시 이동
update product_ingredients set id = id + 100000000000;

-- 2) 기존 순서 그대로 1부터 빈 자리 없이 재배정
with ranked as (
  select id, row_number() over (order by id) as new_id
  from product_ingredients
)
update product_ingredients pi
set id = r.new_id
from ranked r
where pi.id = r.id;

-- identity 원상복구 + 시퀀스를 새 최대값 기준으로 리셋
alter table product_ingredients alter column id set generated always;

select setval(
  pg_get_serial_sequence('product_ingredients', 'id'),
  coalesce((select max(id) from product_ingredients), 1)
);