-- BSTI 피부유형 성분추천 · Supabase(PostgreSQL) 스키마 + 시드
-- 생성 자동화 스크립트 산출물. Supabase SQL Editor에 그대로 실행.
-- 실행 순서: 이 파일 한 번 실행하면 스키마 생성 + 시드 + 채점 함수까지 완료됩니다.

begin;
drop table if exists bsti_type_ingredients, bsti_question_options, bsti_questions, bsti_skin_types, bsti_sunscreens, bsti_ingredients, bsti_axes, bsti_references cascade;

create table bsti_references (code text primary key, title text not null, url text not null);
create table bsti_axes (code text primary key, label text not null, high_pole char(1) not null, high_label text not null, low_pole char(1) not null, low_label text not null, question_count int not null, cutoff numeric not null);
create table bsti_ingredients (id text primary key, name_ko text not null, inci text, role text, category text not null, ref_codes text[] default '{}');
create table bsti_sunscreens (id text primary key, name_ko text not null, note text, ref_codes text[] default '{}');
create table bsti_skin_types (code char(4) primary key, persona_name text not null, tagline text not null, oil char(1) not null, sensitivity char(1) not null, pigment char(1) not null, aging char(1) not null, summary text, care_order text[] not null, sunscreen_id text references bsti_sunscreens(id));
create table bsti_type_ingredients (id bigserial primary key, type_code char(4) references bsti_skin_types(code) on delete cascade, ingredient_id text references bsti_ingredients(id), relation text not null check (relation in ('recommend','avoid')), is_multibenefit boolean default false, sort_order int not null, unique(type_code, ingredient_id, relation));
create table bsti_questions (id int primary key, axis_code text references bsti_axes(code), position int not null, text text not null);
create table bsti_question_options (id bigserial primary key, question_id int references bsti_questions(id) on delete cascade, label text not null, score int not null check (score between 1 and 4), position int not null);

-- references
insert into bsti_references(code,title,url) values ('S1','세라마이드 장벽복구 (Cosmoderma 2024)','https://cosmoderma.org/clinical-evaluation-of-a-topical-ceramide-lotion-on-skin-hydration-and-skin-barrier-in-healthy-volunteers-with-dry-skin/');
insert into bsti_references(code,title,url) values ('S2','세라마이드 지질기전 (PMC5801391)','https://pmc.ncbi.nlm.nih.gov/articles/PMC5801391/');
insert into bsti_references(code,title,url) values ('S3','나이아신아마이드 미백·항노화 (Antioxidants 2021)','https://pmc.ncbi.nlm.nih.gov/articles/PMC8389214/');
insert into bsti_references(code,title,url) values ('S4','병풀+세라마이드 민감성 (JCD 2025)','https://pmc.ncbi.nlm.nih.gov/articles/PMC12274965/');
insert into bsti_references(code,title,url) values ('S5','트라넥사믹+나이아신아마이드 RCT (Sci Rep 2025)','https://www.nature.com/articles/s41598-025-26693-8');
insert into bsti_references(code,title,url) values ('S6','트레티노인 광노화 리뷰 (PMC9112391)','https://pmc.ncbi.nlm.nih.gov/articles/PMC9112391/');
insert into bsti_references(code,title,url) values ('S7','트레티노인 메타분석 (DPC 2025)','https://pmc.ncbi.nlm.nih.gov/articles/PMC12615114/');
insert into bsti_references(code,title,url) values ('S8','나이아신아마이드 다기능 (PMC11047333)','https://pmc.ncbi.nlm.nih.gov/articles/PMC11047333/');
insert into bsti_references(code,title,url) values ('S9','병풀 피부질환 기전 (PMC8627341)','https://pmc.ncbi.nlm.nih.gov/articles/PMC8627341/');
insert into bsti_references(code,title,url) values ('S10','여드름 국소치료 리뷰 (PMC11081083)','https://pmc.ncbi.nlm.nih.gov/articles/PMC11081083/');
insert into bsti_references(code,title,url) values ('S11','아젤라익애씨드 리뷰 (PMC12472904)','https://pmc.ncbi.nlm.nih.gov/articles/PMC12472904/');
insert into bsti_references(code,title,url) values ('S12','비타민C 피부건강 (PMC5579659)','https://pmc.ncbi.nlm.nih.gov/articles/PMC5579659/');
insert into bsti_references(code,title,url) values ('S13','틴티드 자차 기미 RCT (PMC12475913)','https://pmc.ncbi.nlm.nih.gov/articles/PMC12475913/');
insert into bsti_references(code,title,url) values ('S14','기미 맞춤 광보호 (PMC9790748)','https://pmc.ncbi.nlm.nih.gov/articles/PMC9790748/');
insert into bsti_references(code,title,url) values ('S15','무기자차 안전성 (PMC7479990)','https://pmc.ncbi.nlm.nih.gov/articles/PMC7479990/');

-- bsti_axes (cutoff = 2.5 * question_count : 축 점수합 >= cutoff 이면 high_pole)
insert into bsti_axes(code,label,high_pole,high_label,low_pole,low_label,question_count,cutoff) values ('oil','유·수분','O','지성','D','건성',5,12.5);
insert into bsti_axes(code,label,high_pole,high_label,low_pole,low_label,question_count,cutoff) values ('sensitivity','민감도','S','민감','R','저항',6,15.0);
insert into bsti_axes(code,label,high_pole,high_label,low_pole,low_label,question_count,cutoff) values ('pigment','색소','P','색소','N','비색소',4,10.0);
insert into bsti_axes(code,label,high_pole,high_label,low_pole,low_label,question_count,cutoff) values ('aging','노화','W','주름','T','탱탱',5,12.5);

-- bsti_ingredients (권장 성분)
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('cera','세라마이드','Ceramide NP','장벽 복구·경피수분손실 감소','barrier',ARRAY['S1','S2']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('ha','히알루론산','Sodium Hyaluronate','수분 공급·유지','humectant',ARRAY['S1']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('panth','판테놀','Panthenol','보습 + 진정','soothing',ARRAY['S4']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('squa','스쿠알란','Squalane','유분 보강·건조 완화','emollient',ARRAY['S2']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('gly','글리세린','Glycerin','수분 유지','humectant',ARRAY['S1']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('niac','나이아신아마이드','Niacinamide','피지↓·진정·미백·항산화 (멀티벤핏)','multi',ARRAY['S3','S8']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('sal','살리실산 (BHA)','Salicylic Acid','모공 각질·피지 조절','exfoliant',ARRAY['S10']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('zinc','아연','Zinc PCA','피지·진정 보조','sebum',ARRAY['S10']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('reti','레티놀','Retinol','콜라겐 생성·잔주름·각질','retinoid',ARRAY['S6','S7']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('retal','저농도 레티날 / 바쿠치올','Retinal / Bakuchiol','자극 적은 항노화 대안','retinoid',ARRAY['S6']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('adap','아다팔렌','Adapalene','여드름·각질 조절','retinoid',ARRAY['S10']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('aze','아젤라익애씨드','Azelaic Acid','여드름+진정+미백 (멀티벤핏)','multi',ARRAY['S11']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('cica','병풀추출물','Centella Asiatica Extract','항염·진정·장벽 강화','soothing',ARRAY['S4','S9']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('allan','알란토인','Allantoin','진정·보습','soothing',ARRAY['S4']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('bisa','비사보롤','Bisabolol','항염 진정','soothing',ARRAY['S9']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('toco','토코페롤 (비타민E)','Tocopherol','항산화 진정','antioxidant',ARRAY['S12']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('vc','비타민C','Ascorbic Acid','미백 + 콜라겐 합성','multi',ARRAY['S12']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('vcd','비타민C 유도체','Tetrahexyldecyl Ascorbate','저자극 미백·항산화','multi',ARRAY['S12']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('txa','트라넥사믹애씨드','Tranexamic Acid','색소침착 감소','brightening',ARRAY['S5']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('arb','알부틴','Arbutin','티로시나제 억제 미백','brightening',ARRAY['S3']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('lico','감초추출물','Glycyrrhiza Glabra Extract','미백·항염','brightening',ARRAY['S3']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('pept','펩타이드','Peptides','콜라겐 보조·탄력','antiaging',ARRAY['S3']);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('feru','페룰산','Ferulic Acid','항산화·비타민C 안정화','antioxidant',ARRAY['S3']);
-- bsti_ingredients (기피 성분)
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('coconut','코코넛오일','Cocos Nucifera Oil','모공을 막을 수 있음(코메도제닉)','comedogenic',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('ipm','이소프로필미리스테이트','Isopropyl Myristate','코메도제닉','comedogenic',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('lanolin','라놀린','Lanolin','코메도제닉','comedogenic',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('alcohol_hi','고농도 변성알코올','Alcohol Denat.','건조·장벽 손상','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('sls','소듐라우릴설페이트','Sodium Lauryl Sulfate','강한 세정력으로 장벽 손상','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('fragrance','향료','Fragrance/Parfum','자극·알레르기 유발','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('essoil','에센셜오일','Essential Oils','자극 유발 가능','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('bpo','벤조일퍼옥사이드','Benzoyl Peroxide','민감성에 자극','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('glycolic','글리콜산','Glycolic Acid','민감성에 자극(고농도 AHA)','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('reti_hi','고농도 트레티노인/레티놀','High-dose Tretinoin/Retinol','민감성에 자극','irritant',ARRAY[]::text[]);
insert into bsti_ingredients(id,name_ko,inci,role,category,ref_codes) values ('chem_filter','화학필터','Oxybenzone/Octinoxate','접촉 자극·알레르기','irritant',ARRAY[]::text[]);

-- bsti_sunscreens
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('tint','징크옥사이드 + 아이언옥사이드 (틴티드, 젤)','UV·가시광선 차단 → 색소 재발 예방',ARRAY['S13','S14']);
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('tintCream','징크옥사이드 + 아이언옥사이드 (틴티드, 크림)','건성+색소용, 가시광선 차단·보습',ARRAY['S13','S14']);
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('mineral','무기자차 (징크옥사이드·티타늄디옥사이드)','민감성 저자극·광안정',ARRAY['S15']);
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('mineralGel','무기자차 (젤 제형)','지성+민감용 저자극',ARRAY['S15']);
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('organic','유기자차 (젤/플루이드)','백탁 없고 발림성 우수',ARRAY['S15']);
insert into bsti_sunscreens(id,name_ko,note,ref_codes) values ('basic','보습형 광범위 자차','제형 무관, 예방 중심',ARRAY['S14']);

-- bsti_skin_types (16 유형 + 페르소나)
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('OSPW','진정이 먼저인 풀코스 케어 수련생','진정·선크림으로 기초를 다진 뒤 미백→안티에이징 순서로 하나씩 도전.','O','S','P','W','지성 · 민감 · 색소 · 주름 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['진정·장벽','선크림','미백','안티에이징'],'tint');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('OSPT','피지 잡는 순한 톤업 전문가','유분 조절 + 나이아신아마이드 같은 순한 미백으로 잡티 케어.','O','S','P','T','지성 · 민감 · 색소 · 탱탱 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',ARRAY['진정·장벽','선크림','미백'],'tint');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('OSNW','진정 먼저 주름 대비하는 장벽 건축가','장벽을 튼튼히 쌓은 뒤 저자극 레티놀로 노화 대비.','O','S','N','W','지성 · 민감 · 비색소 · 주름 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['진정·장벽','선크림','안티에이징'],'mineralGel');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('OSNT','수분만 챙기는 속예민 물광 미니멀리스트','가벼운 보습과 장벽 케어, 제품은 적게.','O','S','N','T','지성 · 민감 · 비색소 · 탱탱 피부. 피지 조절을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',ARRAY['진정·장벽','선크림'],'mineralGel');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('ORPW','미백·주름 성분 풀가동하는 강철 케어러','튼튼한 피부라 레티놀+비타민C 적극 활용 가능.','O','R','P','W','지성 · 저항 · 색소 · 주름 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['피지·모공','선크림','미백','안티에이징'],'tint');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('ORPT','피지·잡티 잡는 탄탄 톤업러','유분 조절 + 미백 집중, 선크림으로 재발 방지.','O','R','P','T','지성 · 저항 · 색소 · 탱탱 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',ARRAY['피지·모공','선크림','미백'],'tint');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('ORNW','안티에이징에 올인하는 광채 수호자','자극 걱정 없이 레티놀·펩타이드 마음껏.','O','R','N','W','지성 · 저항 · 비색소 · 주름 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['피지·모공','선크림','안티에이징'],'organic');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('ORNT','기본만으로 완성되는 타고난 꿀피부 우등생','세안·보습·선크림 기본 루틴이면 충분.','O','R','N','T','지성 · 저항 · 비색소 · 탱탱 피부. 피지 조절을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',ARRAY['피지·모공','선크림'],'organic');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DSPW','장벽부터 쌓아 올리는 종합 케어 도전자','보습·장벽 최우선, 미백·안티에이징은 순한 것부터 천천히.','D','S','P','W','건성 · 민감 · 색소 · 주름 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['진정·장벽','선크림','미백','안티에이징'],'tintCream');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DSPT','보습 위에 미백 얹는 예민 잡티 진정가','진정+보습으로 바탕을 만들고 저자극 미백 추가.','D','S','P','T','건성 · 민감 · 색소 · 탱탱 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',ARRAY['진정·장벽','선크림','미백'],'tintCream');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DSNW','수분으로 주름 늦추는 보습 레이어링 장인','히알루론산+세라마이드 레이어링, 안티에이징은 펩타이드로.','D','S','N','W','건성 · 민감 · 비색소 · 주름 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['진정·장벽','선크림','안티에이징'],'mineral');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DSNT','보습 하나로 빛나는 미니멀 루틴가','자극 줄이고 보습만 잘해도 충분.','D','S','N','T','건성 · 민감 · 비색소 · 탱탱 피부. 장벽 보습을 기본으로, 저자극 진정 위주로 강한 성분은 저농도·유도체로 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',ARRAY['진정·장벽','선크림'],'mineral');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DRPW','보습 깔고 잡티·주름 공략하는 케어 전략가','보습 베이스 위에 레티놀·비타민C 활용.','D','R','P','W','건성 · 저항 · 색소 · 주름 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['보습·장벽','선크림','미백','안티에이징'],'tintCream');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DRPT','선크림이 무기인 차분한 톤업 관리자','보습+미백 투트랙, 자외선 차단이 핵심.','D','R','P','T','건성 · 저항 · 색소 · 탱탱 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 멜라닌 억제 + 가시광선 차단 자차, 항산화로 노화 예방이 핵심.',ARRAY['보습·장벽','선크림','미백'],'tintCream');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DRNW','항산화로 시간을 붙잡는 맑은 피부 지킴이','보습에 항산화·콜라겐 케어를 더해 주름 속도 늦추기.','D','R','N','W','건성 · 저항 · 비색소 · 주름 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 레티놀·비타민C로 콜라겐 자극이 핵심.',ARRAY['보습·장벽','선크림','안티에이징'],'basic');
insert into bsti_skin_types(code,persona_name,tagline,oil,sensitivity,pigment,aging,summary,care_order,sunscreen_id) values ('DRNT','수분 충전만으로 완성되는 저관리 꿀피부 소유자','보습·선크림 루틴이면 끝.','D','R','N','T','건성 · 저항 · 비색소 · 탱탱 피부. 장벽 보습을 기본으로, 강한 활성성분도 사용 가능하게 관리하고, 자외선차단 예방, 항산화로 노화 예방이 핵심.',ARRAY['보습·장벽','선크림'],'basic');

-- bsti_type_ingredients (유형별 권장/기피 성분 매핑)
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','aze','recommend',true,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','panth','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','bisa','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','vcd','recommend',true,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','retal','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','pept','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','coconut','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','ipm','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPW','lanolin','avoid',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','aze','recommend',true,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','panth','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','bisa','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','vcd','recommend',true,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','toco','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','feru','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','coconut','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','ipm','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSPT','lanolin','avoid',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','aze','recommend',true,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','panth','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','bisa','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','retal','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','pept','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','vcd','recommend',true,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','coconut','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','ipm','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNW','lanolin','avoid',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','aze','recommend',true,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','panth','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','bisa','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','toco','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','feru','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','coconut','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','ipm','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('OSNT','lanolin','avoid',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','zinc','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','txa','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','vc','recommend',true,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','arb','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','reti','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','pept','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','coconut','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','ipm','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPW','lanolin','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','zinc','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','txa','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','vc','recommend',true,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','arb','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','toco','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','feru','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','coconut','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','ipm','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORPT','lanolin','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','zinc','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','reti','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','pept','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','vc','recommend',true,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','coconut','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','ipm','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNW','lanolin','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','niac','recommend',true,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','sal','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','zinc','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','toco','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','feru','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','coconut','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','ipm','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('ORNT','lanolin','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','bisa','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','niac','recommend',true,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','aze','recommend',true,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','vcd','recommend',true,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','retal','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','pept','recommend',false,10);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','alcohol_hi','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPW','sls','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','bisa','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','niac','recommend',true,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','aze','recommend',true,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','vcd','recommend',true,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','toco','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','feru','recommend',false,10);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','alcohol_hi','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSPT','sls','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','bisa','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','retal','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','pept','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','vcd','recommend',true,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','alcohol_hi','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNW','sls','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','cica','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','bisa','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','toco','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','feru','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','fragrance','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','essoil','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','bpo','avoid',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','glycolic','avoid',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','reti_hi','avoid',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','chem_filter','avoid',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','alcohol_hi','avoid',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DSNT','sls','avoid',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','niac','recommend',true,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','txa','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','vc','recommend',true,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','arb','recommend',false,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','reti','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','pept','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','alcohol_hi','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPW','sls','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','squa','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','niac','recommend',true,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','txa','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','vc','recommend',true,7);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','arb','recommend',false,8);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','toco','recommend',false,9);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','feru','recommend',false,10);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','alcohol_hi','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRPT','sls','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','reti','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','pept','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','vc','recommend',true,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','alcohol_hi','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNW','sls','avoid',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','cera','recommend',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','ha','recommend',false,2);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','panth','recommend',false,3);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','squa','recommend',false,4);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','toco','recommend',false,5);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','feru','recommend',false,6);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','alcohol_hi','avoid',false,1);
insert into bsti_type_ingredients(type_code,ingredient_id,relation,is_multibenefit,sort_order) values ('DRNT','sls','avoid',false,2);

-- bsti_questions + options (25문항, score 4=높은극 O/S/P/W)
insert into bsti_questions(id,axis_code,position,text) values (1,'oil',1,'세안 후 아무것도 안 바르고 2~3시간 뒤, T존(이마·코)은?');
insert into bsti_question_options(question_id,label,score,position) values (1,'번들거려요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (1,'약간 유분이 돌아요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (1,'별 변화 없어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (1,'당기고 건조해요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (2,'oil',2,'모공은 어떤 편인가요?');
insert into bsti_question_options(question_id,label,score,position) values (2,'크고 잘 보여요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (2,'코 주변만 보여요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (2,'거의 안 보여요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (2,'아주 작아요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (3,'oil',3,'보습제를 안 발라도 피부가 편한가요?');
insert into bsti_question_options(question_id,label,score,position) values (3,'안 발라도 편해요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (3,'가끔 당겨요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (3,'자주 당겨요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (3,'항상 당기고 각질이 일어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (4,'oil',4,'오후가 되면 얼굴 전체가?');
insert into bsti_question_options(question_id,label,score,position) values (4,'번들거려요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (4,'T존만 번들거려요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (4,'그대로예요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (4,'더 건조해져요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (5,'oil',5,'피부 표면을 만지면?');
insert into bsti_question_options(question_id,label,score,position) values (5,'매끈하고 촉촉해요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (5,'보통이에요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (5,'약간 까슬해요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (5,'거칠고 푸석해요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (6,'sensitivity',6,'최근 4주간 홍조·따가움·발진 같은 자극 증상이 있었나요?');
insert into bsti_question_options(question_id,label,score,position) values (6,'자주 있었어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (6,'가끔 있었어요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (6,'드물었어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (6,'전혀 없었어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (7,'sensitivity',7,'새 스킨케어를 쓰면 붉어지거나 따가운가요?');
insert into bsti_question_options(question_id,label,score,position) values (7,'항상 그래요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (7,'자주 그래요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (7,'가끔요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (7,'거의 없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (8,'sensitivity',8,'향료·에센셜오일이 든 제품을 쓰면?');
insert into bsti_question_options(question_id,label,score,position) values (8,'자극·발진이 생겨요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (8,'가끔 불편해요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (8,'괜찮은 편이에요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (8,'전혀 문제없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (9,'sensitivity',9,'여드름·뾰루지가 나는 편인가요?');
insert into bsti_question_options(question_id,label,score,position) values (9,'자주 나요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (9,'가끔 나요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (9,'드물어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (9,'거의 안 나요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (10,'sensitivity',10,'레티놀·산(AHA/BHA) 성분에 반응한 적이 있나요?');
insert into bsti_question_options(question_id,label,score,position) values (10,'여러 번 있어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (10,'한두 번요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (10,'잘 모르겠어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (10,'없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (11,'sensitivity',11,'피부과에서 민감성·주사(홍조)·아토피 얘기를 들은 적이?');
insert into bsti_question_options(question_id,label,score,position) values (11,'진단받았어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (11,'의심된다 들었어요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (11,'아니요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (11,'전혀요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (12,'pigment',12,'잡티·기미·주근깨가 있나요?');
insert into bsti_question_options(question_id,label,score,position) values (12,'많아요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (12,'보통이에요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (12,'조금 있어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (12,'거의 없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (13,'pigment',13,'여드름·상처 후 갈색 자국(색소침착)이?');
insert into bsti_question_options(question_id,label,score,position) values (13,'오래 남아요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (13,'한동안 남아요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (13,'금방 옅어져요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (13,'거의 안 남아요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (14,'pigment',14,'햇볕을 쬐면 피부가?');
insert into bsti_question_options(question_id,label,score,position) values (14,'쉽게 검어져요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (14,'조금 검어져요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (14,'별로 안 변해요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (14,'거의 그대로예요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (15,'pigment',15,'다크스팟·톤을 개선하고 싶나요?');
insert into bsti_question_options(question_id,label,score,position) values (15,'톤이 고르지 않아 꼭 개선하고 싶어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (15,'개선하고 싶은 편이에요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (15,'별로 신경 안 써요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (15,'톤이 고르고 필요 없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (16,'aging',16,'표정을 풀어도 잔주름이 보이나요?');
insert into bsti_question_options(question_id,label,score,position) values (16,'뚜렷하게 보여요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (16,'조금 보여요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (16,'미세하게요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (16,'없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (17,'aging',17,'눈가·이마·팔자에 주름이?');
insert into bsti_question_options(question_id,label,score,position) values (17,'깊어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (17,'보이기 시작했어요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (17,'미세해요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (17,'없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (18,'aging',18,'자외선 노출과 자차(선크림) 습관은?');
insert into bsti_question_options(question_id,label,score,position) values (18,'노출 많고 자차를 거의 안 발라요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (18,'노출 있고 가끔 발라요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (18,'실내 위주에 자주 발라요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (18,'실내 위주에 매일 꼼꼼히 발라요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (19,'aging',19,'흡연·수면부족·불규칙한 식습관 등 노화에 안 좋은 습관이?');
insert into bsti_question_options(question_id,label,score,position) values (19,'여러 개 해당돼요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (19,'한두 개 있어요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (19,'거의 없어요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (19,'전혀 없어요',1,4);
insert into bsti_questions(id,axis_code,position,text) values (20,'aging',20,'피부 탄력·처짐은 어떤가요?');
insert into bsti_question_options(question_id,label,score,position) values (20,'눈에 띄게 떨어졌어요',4,1);
insert into bsti_question_options(question_id,label,score,position) values (20,'약간 떨어졌어요',3,2);
insert into bsti_question_options(question_id,label,score,position) values (20,'거의 그대로예요',2,3);
insert into bsti_question_options(question_id,label,score,position) values (20,'탄탄해요',1,4);

-- 채점 규칙: 축별 선택 score 합 >= cutoff 이면 high_pole, 아니면 low_pole → oil,sensitivity,pigment,aging 순 4글자 코드
-- p_answers 예: {"1":4,"2":3, ... ,"20":2}  (question_id -> 선택한 보기 score)
create or replace function bsti_compute_code(p_answers jsonb) returns char(4) language plpgsql as $$
declare r record; s numeric; v_code text := '';
begin
  for r in select * from bsti_axes a order by array_position(array['oil','sensitivity','pigment','aging'], a.code) loop
    select coalesce(sum( (p_answers ->> q.id::text)::numeric ),0) into s from bsti_questions q where q.axis_code = r.code;
    v_code := v_code || case when s >= r.cutoff then r.high_pole else r.low_pole end;
  end loop;
  return v_code;
end $$;

-- 사용자 진단 결과 저장용(선택) 예시 테이블
create table if not exists bsti_user_diagnoses (id bigserial primary key, user_id uuid, answers jsonb not null, result_code char(4) references bsti_skin_types(code), created_at timestamptz default now());
-- INSERT 시 result_code := bsti_compute_code(answers) 로 채우면 됨.

-- 편의 함수: 답변 → 코드 + 유형 + 권장/기피 성분 + 자차 를 JSON 한 번에
create or replace function bsti_diagnose(p_answers jsonb)
returns jsonb language sql stable as $$
  with c as (select bsti_compute_code(p_answers) as code)
  select jsonb_build_object(
    'code', c.code,
    'type', (select jsonb_build_object('persona_name', t.persona_name, 'tagli